### ISSUE TITLE
Any different with “kubernetes-client/csharp” ?

### ISSUE THREAD

**Issue by CrazyBBer** [tintoy/dotnet-kube-client#17]
hi, guys :

any different with https://github.com/kubernetes-client/csharp  or providing another option ?

**Comment by CrazyBBer** [comment]
i got it, thank u.

**Comment by tintoy** [comment]
Hi! Yep, there's an official client; personally I use this one because it better fits my use case and style but the official client's just fine (I also contribute to that one :grin:).

I designed this one to be clean and extensible in ways that the official client is not, but if that doesn't sound like your use-case then you're probably better off using the official one.
