### ISSUE TITLE
configmap change is not fired with "reloadOnChange: true"

### ISSUE THREAD

**Issue by smartpcr** [tintoy/dotnet-kube-client#78]
in sample "ConfigFromConfigMap", change callback is never fired.

**Comment by tintoy** [comment]
Hi - thanks for reporting! Will take a look at this tomorrow :)

**Comment by tintoy** [comment]
Turns out this is due to a combination of factors. The main problem was that change tokens are single-use; once the change callback is invoked, you have to request a new token and re-register your callback.

I've updated the sample, and added logging for the config provider to improve the diagnostic experience :)

Will publish a new build shortly.

**Comment by tintoy** [comment]
Published v0.2.12.

**Comment by tintoy** [comment]
Can you try out the new version and let me know if it works for you?

**Comment by tintoy** [comment]
Published v0.2.13. Turns out I misunderstood how config reloads are supposed to work. I have verified that the updated config is now correct.

Note that, regardless of the config key case used when creating the ConfigMap, K8s transforms the config key names to lower-case for some reason (but the dictionary is case-insensitive so things still work correctly).

**Comment by tintoy** [comment]
Closing #82 (feel free to reopen if you still have this problem).
