### ISSUE TITLE
Support for .NET v4.7.2

### ISSUE THREAD

**Issue by brobichaud** [tintoy/dotnet-kube-client#83]
We are trying to migrate a solution to .NET 4.7.2 and are hitting issues with this component. Is there any plan to support 4.7.2 coming?

**Comment by tintoy** [comment]
Hi - what sort of issues are you encountering?

**Comment by tintoy** [comment]
Most of the packages target `netstandard1.4`, from memory, so this should include .NET 4.7.1.

The websockets stuff is only for .NET Core because the full framework’s websockets implementation doesn’t doesn’t have proper support for client certs on websockets (again, this is from memory, I’d have to go look over some of our closed issues to be sure).

**Comment by tintoy** [comment]
Here’s the issue that describes the problem:

https://github.com/kubernetes-client/csharp/issues/102

(as far as I know, the full framework uses WinHTTP as well for this so the same issue applies)

**Comment by JonathanHope** [comment]
Hi another team member here,

When I first mass upgraded all of the projects I was getting errors related to the System.ValueTuple. I upgraded to the latest version of the package but the error persisted. I finally uninstalled the package and System.ValueTuple and the reinstalled everything and it started to build.

The one remaining issue is if I upgrade YamlDotNet from version 5 to 6 I get a runtime error of:

Could not load file or assembly 'YamlDotNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Thanks,

**Comment by tintoy** [comment]
Hi - I suspect that’s because v6 has breaking API changes relative to v5 (which is what KubeClient is built against) and so they have changed the assembly version. Generally, major version number changes indicate a that breaking changes have been made between versions...

You could try adding a binding redirect to your app.config / web.config to see if that fixes it. This issue might be similar:

https://github.com/andrewlock/NetEscapades.Configuration/issues/26

Is there a particular reason you need v6 rather than v5?

**Comment by tintoy** [comment]
PS. Further down in the comments on that linked issue, it sounds like there was a problem with some of the v5 assemblies being built to have an assembly version of 0.0.0.0. When I get a chance I’ll see what assembly versions are being used in KubeClient and whether we can upgrade to a newer minor version of v5 (can’t upgrade KubeClient to v6 of YamlDotNet without forcing anyone who uses KubeClient to upgrade their YamlDotNet to v6 as well).

**Comment by JonathanHope** [comment]
We don't need V6. Thanks for the prompt responses on this.

**Comment by tintoy** [comment]
I'm closing this issue, since it sounds like it's resolved. Feel free to reopen if you still have questions :)
